version: '3.8'

services:
  penny-planner-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        - NODE_ENV=development
        - DATABASE_URL=postgres://postgres:password@penny-planner-postgres:5432/penny-planner
    depends_on:
      - penny-planner-postgres
    env_file:
      - ./src/services/db/.env
    volumes:
      - ./src:/usr/src/app/src
      - ./app.js:/usr/src/app/app.js
      - /node_modules
    container_name: penny-planner-api
    networks:
      - app-tier
    expose:
      - '3001'
    ports:
      - '3001:3001'
    command: npm start

  penny-planner-postgres:
    build:
      context: ./src/services/db
      dockerfile: Dockerfile
    container_name: penny-planner-postgres
    user: postgres
    env_file:
      - ./src/services/db/.env
    volumes:
      - ./src/services/db/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app-tier

  redis-cache:
    build:
      context: ./src/services/cache
      dockerfile: Dockerfile
    container_name: redis-cache
    env_file:
      - ./src/services/cache/.env
    environment:
      - REDIS_URL=redis://cache:6379
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - app-tier
    volumes:
      - ./src/services/cache/cache:/data

networks:
  app-tier:
    driver: bridge
